### ISSUE TITLE
Clean-up before v0.3.0 release

### ISSUE THREAD

**Issue by dzhoshkun** [gift-surg/Xono2L#34]
PR #26 has introduced a few changes that need to be addressed.

* [ ] the choice of linking against device-specific APIs is unclear
* [ ] #33 needs to be addressed
* [ ] #27 (also need to document the zlib dependency)
* [ ] Not a terrible problem, but #25 
* [ ] Check #26 changes for any other issues.
